[source.crates-io]
replace-with = 'mirror'

[source.mirror]
registry = "https://mirrors.tuna.tsinghua.edu.cn/git/crates.io-index.git"

[target.aarch64-unknown-linux-gnu]
linker = "aarch64-linux-gnu-gcc"
