[default_view]

keymap = [
	{ keys = [ "q" ],		command = "close_tab" },
	{ keys = [ "Q" ],		command = "quit --output-current-directory" },

	{ keys = [ "R" ],		command = "reload_dirlist" },
	{ keys = [ "." ],		command = "toggle_hidden" },
	{ keys = [ "\t" ],		command = "tab_switch 1" },
	{ keys = [ "backtab" ],		command = "tab_switch -1" },

	{ keys = [ "alt+1" ],		command = "tab_switch_index 1" },
	{ keys = [ "alt+2" ],		command = "tab_switch_index 2" },
	{ keys = [ "alt+3" ],		command = "tab_switch_index 3" },
	{ keys = [ "alt+4" ],		command = "tab_switch_index 4" },
	{ keys = [ "alt+5" ],		command = "tab_switch_index 5" },

	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "arrow_left" ],	command = "cd .." },
	{ keys = [ "arrow_right" ],	command = "open" },
	{ keys = [ "\n" ],		command = "open" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },
	{ keys = [ "page_up" ],		command = "cursor_move_page_up" },
	{ keys = [ "page_down" ],	command = "cursor_move_page_down" },
	{ keys = [ "ctrl+u" ],  	command = "cursor_move_page_up 0.5" },
	{ keys = [ "ctrl+d" ], 		command = "cursor_move_page_down 0.5" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "h" ],		command = "cd .." },
	{ keys = [ "l" ],		command = "open" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "y", "y" ],		command = "copy_files" },
	{ keys = [ "p" ],		command = "paste_files" },

	{ keys = [ "D" ],		command = "delete_files" },

	{ keys = [ "a" ],		command = ":touch " },
	{ keys = [ "A" ],		command = ":mkdir " },
	{ keys = [ "r" ],		command = ":rename " },

	{ keys = [ "/" ],		command = ":search " },
	{ keys = [ "f" ],		command = "search_fzf" },
	{ keys = [ "alt+c" ],		command = "subdir_fzf" },
	{ keys = [ "z" ],		command = "zi" },
	{ keys = [ "n" ],		command = "search_next" },
	{ keys = [ "N" ],		command = "search_prev" },
]

[task_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]

[help_view]

keymap = [
	# arrow keys
	{ keys = [ "arrow_up" ],	command = "cursor_move_up" },
	{ keys = [ "arrow_down" ],	command = "cursor_move_down" },
	{ keys = [ "home" ],		command = "cursor_move_home" },
	{ keys = [ "end" ],		command = "cursor_move_end" },

	# vim-like keybindings
	{ keys = [ "j" ],		command = "cursor_move_down" },
	{ keys = [ "k" ],		command = "cursor_move_up" },
	{ keys = [ "g", "g" ],		command = "cursor_move_home" },
	{ keys = [ "G" ],		command = "cursor_move_end" },

	{ keys = [ "w" ],		command = "show_tasks" },
	{ keys = [ "escape" ],		command = "show_tasks" },
]
