theme = "slick"
icons = "awesome"

[[block]]
block = "net"
device = "wlo1"
format = "{ssid} {speed_down;K*b}"
interval = 10

[[block]]
block = "disk_space"
path = "/"
info_type = "used"
format = "{icon} {used}"
alert = 210
warning = 200

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
display_type = "memory"
icons = true
clickable = true
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "cpu"
interval = 5
format = "{utilization} {frequency}"

[[block]]
block = "temperature"
collapsed = false
interval = 60
format = "{max}"
chip = "*-isa-*"

[[block]]
block = "battery"
interval = 60
format = "{percentage}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
