theme = "slick"
icons = "awesome"

[[block]]
block = "memory"
format_mem = "{mem_used}/{mem_total}"
display_type = "memory"
icons = true
clickable = true
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 300
format = "{percentage}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
format = "%a %d/%m %R"
