[[block]]
block = "memory"
interval = 60
warning_mem = 80
warning_swap = 80
critical_mem = 95
critical_swap = 95

[[block]]
block = "battery"
interval = 300
format = "{percentage}"

[[block]]
block = "sound"

[[block]]
block = "time"
interval = 60
